#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Starting pre-commit checks: styling, type checking, and more.'

# Check Prettier standards
npm run check-format || (
    echo '❌ Code styling check failed.
          Please run npm run format, add changes, and try committing again.';
    exit 1;
)

# Uncomment this section if ESLint checks are needed
# Check ESLint Standards
# npm run check-lint || (
#     echo '❌ Linting check failed.
#           Please fix the issues listed above, add changes, and try committing again.';
#     exit 1;
# )

# Check TypeScript standards
npm run check-types || (
    echo '❌ TypeScript type check failed.
          Please address the errors listed above and try committing again.';
    exit 1;
)

# Uncomment this section if build checks are needed
# Check build process
# npm run build || (
#     echo '❌ Build failed.
#           Please fix the issues preventing the build from succeeding and try committing again.';
#     exit 1;
# )

# If everything passes, allow the commit
echo '✅ All checks passed. Proceeding with commit.'